export const TASKS_GET_START = 'TASKS_GET_START';
export const TASKS_GET_SUCCESS = 'TASKS_GET_SUCCESS';
export const TASKS_GET_ERROR = 'TASKS_GET_ERROR';

export const TASKS_CREATE_START = 'TASKS_CREATE_START';
export const TASKS_CREATE_SUCCESS = 'TASKS_CREATE_SUCCESS';
export const TASKS_CREATE_ERROR = 'TASKS_CREATE_ERROR';

export const TASKS_UPDATE_START = 'TASKS_UPDATE_START';
export const TASKS_UPDATE_SUCCESS = 'TASKS_UPDATE_SUCCESS';
export const TASKS_UPDATE_ERROR = 'TASKS_UPDATE_ERROR';